### ISSUE TITLE
Repo root does not include copy of license

### ISSUE THREAD

**Issue by ctsrc** [kendricktan/ledger-analytics#1]
Including a copy of the license (MIT according to your package.json) will allow GitHub to mark the repo with which license is being used, making it easier for visitors to see this information at a glance. Please add a copy of the MIT license to your repo root, thanks :)

**Comment by kendricktan** [comment]
Done! Thanks for the reminder ahaha I totally forgot to add this it.
https://github.com/kendricktan/ledger-analytics/commit/b90dbb038da0609a082cdac4eab161fb3ca9c2da
