### ISSUE TITLE
Getting 404s for resources, causes blank page

### ISSUE THREAD

**Issue by akerl** [kendricktan/ledger-analytics#2]
I ran the following:

```
npm install -g ledger-analytics
ledger-analytics -f core.ldg
```

When I browse to http://localhost:3000 , I get a blank page. Checking the chrome dev console, it's 404ing on all the CSS / JS resources. As an example:

![image](https://user-images.githubusercontent.com/491209/44666941-30d9f300-aa22-11e8-8bdb-b94332a887ba.png)

**Comment by akerl** [comment]
it looks like this is because https://raw.githubusercontent.com/kendricktan/ledger-analytics/master/frontend/index.html embeds in your username/reponame in the path?

**Comment by kendricktan** [comment]
Seems like `npm run build` automatically appends it for some reason. I'm not too familiar with the build process but have manually removed it from `index.html` on version `0.1.3a`. Try it out :) https://github.com/kendricktan/ledger-analytics/commit/4f3ee700d27dfe1265fe29c3e7f6facc02084488

**Comment by akerl** [comment]
Looks good!
