### ISSUE TITLE
How to - In growth view mouseover add a space between currency and amount?

### ISSUE THREAD

**Issue by RidaAyed** [kendricktan/ledger-analytics#6]
Hi
Having a space between currency and amount would increase readabilty. 

How can I do this?

![Screenshot](https://i.imgur.com/omsAtli.png)

**Comment by kendricktan** [comment]
Hello,

You can manually add a space between `baseCommodity` and `toFixed(2)` here
https://github.com/kendricktan/ledger-analytics/blob/master/src/components/charts/stacked-area.js#L106

I'm currently fixing up the codebase so I won't be updating it globally for a while

**Comment by kendricktan** [comment]
This is fixed on the latest release :smile:
